version: '3'
services:
  backend:
    build: ./Components/Backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DBUSER=postgres
      - DBHOST=db
      - DBPASSWORD=postgres
      - DBNAME=main
      - SECRET=cookie
      - AWS_SECRET=blahblahblah
      - AWS_ID=AKIARC56D5EQED5MOMMD
      - AWS_S3_BUCKET_NAME=csci-reality-proj
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # frontend:
  #   build: ./Components/frontend-vue
  #   ports:
  #     - 8080:8080
    
